wandb_version: 1

epochs:
  desc: null
  value: 75000
learning_rate:
  desc: null
  value: 0.001
cell_type:
  desc: null
  value: LSTM
opti:
  desc: null
  value: SDG
layers:
  desc: null
  value: 1
dataset:
  desc: null
  value: eng-spa
hidden_size:
  desc: null
  value: 256
dropout:
  desc: null
  value: 0.1
_wandb:
  desc: null
  value:
    python_version: 3.8.5
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716812168
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      - 61
      4: 3.8.5
      5: 0.17.0
      8:
      - 5
      13: linux-x86_64
