wandb_version: 1

epochs:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.001
cell_type:
  desc: null
  value: GRU
opti:
  desc: null
  value: SDG
layers:
  desc: null
  value: 1
dataset:
  desc: null
  value: eng-spa
hidden_size:
  desc: null
  value: 256
dropout:
  desc: null
  value: 0.1
_wandb:
  desc: null
  value:
    python_version: 3.9.0
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717016833
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.9.0
      5: 0.17.0
      8:
      - 3
      - 5
      13: windows-amd64
