wandb_version: 1

epochs:
  desc: null
  value: 75000
learning_rate:
  desc: null
  value: 0.001
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716634529
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      - 61
      4: 3.8.16
      5: 0.17.0
      8:
      - 5
      13: linux-x86_64
