wandb_version: 1

epochs:
  desc: null
  value: 50
learning_rate:
  desc: null
  value: 0.001
cell_type:
  desc: null
  value: GRU
opti:
  desc: null
  value: Adam
dataset:
  desc: null
  value: eng-spa
hidden_size:
  desc: null
  value: 256
batch_size:
  desc: null
  value: 128
_wandb:
  desc: null
  value:
    python_version: 3.11.0
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717232435
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 13
      - 15
      - 16
      - 23
      - 61
      4: 3.11.0
      5: 0.17.0
      8:
      - 3
      - 5
      13: windows-amd64
