name: py38_default
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - binutils_impl_linux-64=2.33.1=he6710b0_7
  - binutils_linux-64=2.33.1=h9595d00_15
  - blas=1.0=mkl
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.3.11=h06a4308_0
  - certifi=2024.2.2=py38h06a4308_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - entrypoints=0.4=py38h06a4308_0
  - expat=2.6.2=h6a678d5_0
  - ffmpeg=4.2.2=h20bf706_0
  - fontconfig=2.14.1=h4c34cd2_2
  - freetype=2.12.1=h4a9f257_0
  - gcc_impl_linux-64=7.3.0=habb00fd_1
  - gcc_linux-64=7.3.0=h553295d_15
  - giflib=5.2.1=h5eee18b_3
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - gxx_impl_linux-64=7.3.0=hdf63c60_1
  - gxx_linux-64=7.3.0=h553295d_15
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.12.1=h2b7332f_3
  - icu=58.2=he6710b0_3
  - idna=3.7=py38h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h5eee18b_1
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - lerc=3.0=h295c915_0
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcups=2.4.2=h2d74bed_1
  - libcurl=8.7.1=h251f7ec_0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.78.4=hdc74915_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libllvm14=14.0.6=hdb19cb5_3
  - libnetcdf=4.8.1=h14805e7_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.17=hdbd6064_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.4=hcbfbd50_0
  - libzip=1.8.0=h6ac8c49_1
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py38h5eee18b_0
  - mkl=2021.4.0=h06a4308_640
  - mysql=5.7.24=h721c034_2
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py38h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - nodejs=12.4.0=he1b5a44_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=3.0.13=h7f8727e_2
  - packaging=23.2=py38h06a4308_0
  - pcre2=10.42=hebb0a14_1
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - python=3.8.19=h955ad1f_0
  - python-dateutil=2.9.0post0=py38h06a4308_2
  - python_abi=3.8=2_cp38
  - pytorch-mutex=1.0=cpu
  - pyyaml=6.0.1=py38h5eee18b_0
  - qt-main=5.15.2=h7358343_9
  - readline=8.2=h5eee18b_0
  - setuptools=69.5.1=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=0.12.1=py38_cpu
  - urllib3=2.2.1=py38h06a4308_0
  - wget=1.21.4=h251f7ec_1
  - wheel=0.43.0=py38h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
      - argparse==1.4.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - contourpy==1.1.1
      - cycler==0.12.1
      - docker-pycreds==0.4.0
      - fonttools==4.52.4
      - gitdb==4.0.11
      - gitpython==3.1.43
      - importlib-resources==6.4.0
      - joblib==1.4.2
      - kiwisolver==1.4.5
      - matplotlib==3.7.5
      - nltk==3.8.1
      - numpy==1.24.4
      - pandas==1.5.3
      - pillow==10.3.0
      - pip==24.0
      - platformdirs==4.2.2
      - protobuf==4.25.3
      - psutil==5.9.8
      - pyparsing==3.1.2
      - regex==2024.5.15
      - requests==2.32.2
      - scipy==1.9.1
      - sentry-sdk==2.3.1
      - setproctitle==1.3.3
      - smmap==5.0.0
      - torch==1.12.1+cu113
      - torchvision==0.13.1+cu113
      - tqdm==4.66.4
      - typing-extensions==4.12.0
      - wandb==0.17.0
      - zipp==3.19.0
prefix: /anaconda/envs/py38_default
